name: naturerepublic
description: Nature Republic E-commerce App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.1.1
  flutter_dotenv: ^5.1.0
  json_annotation: ^4.8.1
  smooth_page_indicator: ^1.1.0
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.3.4
  cached_network_image: ^3.4.1
  google_fonts: ^6.1.0
  webview_flutter: ^4.4.2
  # WooCommerce dependencies
  dio: ^5.4.0
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.8.0
  share_plus: ^10.1.3
  flutter_html: ^3.0.0-beta.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - .env
